apiVersion: v1
kind: Pod
metadata:
  name: alpine-plus
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: alpine-plus
    image: docker.io/dmilan/alpine-plus:latest
  hostNetwork: true
  dnsPolicy: Default

